/*  CREATE TABLE SUPPLIER */ 
CREATE TABLE SUPPLIER(SUPP_ID INT PRIMARY KEY, SUPP_NAME VARCHAR(50) NOT NULL, SUPP_CITY VARCHAR(50) NOT NULL, SUPP_PHONE VARCHAR(50) NOT NULL);

/* CREATE TABLE CUSTOMER */
 CREATE TABLE CUSTOMER(CUS_ID INT PRIMARY KEY,CUS_NAME VARCHAR(20) NOT NULL,CUS_PHONE VARCHAR(10) NOT NULL,CUS_CITY VARCHAR(30) NOT NULL,CUS_GENDER CHAR);

/* CREATE TABLE CATEGORY */
 CREATE TABLE CATEGORY(CAT_ID INT PRIMARY KEY,CAT_NAME VARCHAR(20) NOT NULL);

/* CREATE TABLE PRODUCT */
 CREATE TABLE PRODUCT(PRO_ID INT PRIMARY KEY,PRO_NAME VARCHAR(20) NOT NULL DEFAULT 'Dummy',PRO_DESC VARCHAR(60),CAT_ID INT,CONSTRAINT FK_CATEGORY FOREIGN KEY (CAT_ID) REFERENCES CATEGORY(CAT_ID));

/* CREATE TABLE SUPPLIER_PRICING */
 CREATE TABLE SUPPLIER_PRICING(PRICING_ID INT PRIMARY KEY,PRO_ID INT,SUPP_ID INT,SUPPLIER_PRICE INT DEFAULT 0,CONSTRAINT FK_PRODUCT FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID), CONSTRAINT FK_SUPPLIER FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER(SUPP_ID));

/* CREATE TABLE ORDERS */
 CREATE TABLE ORDERS(ORD_ID INT PRIMARY KEY,ORD_AMOUNT INT NOT NULL,ORD_DATE DATE NOT NULL,CUS_ID INT,PRICING_ID INT,CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),CONSTRAINT FK_SUPPLIER_PRICING FOREIGN KEY (PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID));

/* CREATE TABLE RATING */
 CREATE TABLE RATING(RAT_ID INT PRIMARY KEY,ORD_ID INT,RAT_RATSTARTS INT NOT NULL, CONSTRAINT FK_ORDERS FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID));
